name: Publicar Reportes en GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Preparar Reporte Gatling para Publicación
        run: |
          LAST_GATLING_REPORT=$(ls -dt target/gatling/*/ | head -n 1)
          echo "Último reporte de Gatling: $LAST_GATLING_REPORT"
          mkdir -p gh-pages/gatling-report
          cp -r "$LAST_GATLING_REPORT"* gh-pages/gatling-report/

      - name: Preparar Reporte Karate (Cluecumber) para Publicación
        run: |
          mkdir -p gh-pages/karate-report
          cp -r target/cluecumber-report/* gh-pages/karate-report/

      - name: Publicar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
          clean: true
